export default {
  title: 'Classic Rock',
  author: 'Renato Rossi',
  photo: 'https://img00.deviantart.net/6a36/i/2017/055/f/4/classic_rock_playlist_cover_by_azucar95-db06qcu.jpg',
  description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  songList: [
    {
      src: 'https://newtabs.stream/stream/MvWBZB:qpP3rB',
      type: 'audio/mpeg',
      album: 'Spirito',
      artist: 'Litfiba',
      title: 'Lacio Drom (Buon Viaggio)',
      photo: 'https://images-na.ssl-images-amazon.com/images/I/91G-2o3aoNL._SL1500_.jpg',
    },
    {
      src: 'https://newtabs.stream/stream/GvWBZB:nUz3rB',
      type: 'audio/mpeg',
      album: 'Fear of the Dark',
      artist: 'Iron Maiden',
      title: 'Fear of the Dark',
      photo: 'http://www.fabiosroom.eu/it/wp-content/authors/iron-maiden/cover-fear-of-the-dark.jpg',
    },
    {
      src: 'https://newtabs.stream/stream/buWBZB:fHx1rB',
      type: 'audio/mpeg',
      album: 'Paranoid',
      artist: 'Black Sabbath',
      title: 'Paranoid',
      photo: 'https://sentireascoltare.com/wp-content/uploads/2013/01/black-sabbath_Paranoid.jpg',
    },
    // {
    //   src: 'https://youtubemp3api.com/@download/128-5b2ffe40eefc5-5616000-351/mp3/8aQRq9hhekA/Black%2BSabbath%2B-%2BIron%2BMan.mp3',
    //   type: 'audio/mpeg',
    //   album: 'Paranoid',
    //   artist: 'Black Sabbath',
    //   title: 'Iron Man',
    //   photo: 'http://i41.tinypic.com/2mqw8ea.jpg',
    // },
    // {
    //   src: 'https://youtubemp3api.com/@download/128-5b2ffeed5ab32-6624000-414/mp3/_FrOQC-zEog/Pink%2BFloyd%2B-%2BComfortably%2Bnumb.mp3',
    //   type: 'audio/mpeg',
    //   album: 'The Wall',
    //   artist: 'Pink Floyd',
    //   title: 'Comfortably numb',
    //   photo: 'http://i41.tinypic.com/2mqw8ea.jpg',
    // },
    // {
    //   src: 'https://youtubemp3api.com/@download/128-5b30020aed3e9-5120000-320/mp3/n_GFN3a0yj0/AC-DC%2B-%2BThunderstruck%2B%2528from%2BLive%2Bat%2BRiver%2BPlate%2529.mp3',
    //   type: 'audio/mpeg',
    //   album: 'Live at River Plate',
    //   artist: 'AC/DC',
    //   title: 'Thunderstruck',
    //   photo: 'http://i41.tinypic.com/2mqw8ea.jpg',
    // },
    // {
    //   src: 'https://youtubemp3api.com/@download/128-5b3000acba7d5-6224000-389/mp3/Lli99OmkPwM/Metallica%2B-%2BNothing%2BElse%2BMatters%2B2007%2BLive%2BVideo%2BFull%2BHD.mp3',
    //   type: 'audio/mpeg',
    //   album: 'Live 2007',
    //   artist: 'Metallica',
    //   title: 'Nothing Else Matters',
    //   photo: 'http://i41.tinypic.com/2mqw8ea.jpg',
    // },
    // {
    //   src: 'https://youtubemp3api.com/@download/128-5b300182742e4-4032000-252/mp3/2G5rfPISIwo/Iron%2BMaiden%2B-%2BThe%2BTrooper.mp3',
    //   type: 'audio/mpeg',
    //   album: 'Piece of Mind',
    //   artist: 'Iron Maiden',
    //   title: 'The Trooper',
    //   photo: 'http://i41.tinypic.com/2mqw8ea.jpg',
    // },
  ],
};
